alter table clients
  add column if not exists short_name text,
  add column if not exists industry text,
  add column if not exists description text,
  add column if not exists contact_name text,
  add column if not exists designation text,
  add column if not exists address_line1 text,
  add column if not exists address_line2 text,
  add column if not exists city text,
  add column if not exists state text,
  add column if not exists postal_code text,
  add column if not exists country text,
  add column if not exists tax_id text,
  add column if not exists payment_terms text,
  add column if not exists currency text;
