import { NextResponse } from 'next/server'
import { z } from 'zod'
import { requireAuthorization } from '@/lib/server/authorization'
import { db } from '@/lib/server/db'
import { apiError, AppError } from '@/lib/server/errors'

export const runtime = 'nodejs'
const input = z.object({ clientId: z.string().uuid(), projectId: z.string().uuid().nullable().optional(), title: z.string().trim().min(2).max(240), dueAt: z.string().datetime().nullable().optional() })

export async function GET() { try { const context = await requireAuthorization(); if (!context.permissions.includes('approvals.view')) throw new AppError('FORBIDDEN', 'You do not have permission to view approvals.', 403); const items = await db()`select a.id,a.title,a.status,a.due_at,a.client_id,c.name as client_name,a.project_id,p.name as project_name,a.created_at,coalesce(requester.display_name,requester.name) as requested_by from approvals a join clients c on c.id=a.client_id left join projects p on p.id=a.project_id join users requester on requester.id=a.requested_by_user_id where a.workspace_id=${context.workspaceId} and a.archived_at is null and (${context.role}<>'MEMBER' or c.owner_user_id=${context.userId}::uuid) order by coalesce(a.due_at,a.updated_at) asc`; return NextResponse.json({ items }) } catch (error) { return apiError(error) } }
export async function POST(request: Request) { try { const context = await requireAuthorization(); if (!context.permissions.includes('approvals.request')) throw new AppError('FORBIDDEN', 'You do not have permission to request approvals.', 403); const data=input.parse(await request.json()); const [client]=await db()<{id:string}[]>`select id from clients where id=${data.clientId}::uuid and workspace_id=${context.workspaceId} and archived_at is null and (${context.role}<>'MEMBER' or owner_user_id=${context.userId}::uuid)`; if(!client)throw new AppError('VALIDATION_ERROR','Choose an accessible active client.',400); if(data.projectId){const [project]=await db()<{id:string}[]>`select id from projects where id=${data.projectId}::uuid and workspace_id=${context.workspaceId} and client_id=${data.clientId}::uuid and archived_at is null`;if(!project)throw new AppError('VALIDATION_ERROR','Project must belong to the selected client.',400)} const [item]=await db().begin(async sql=>{const [created]=await sql`insert into approvals(workspace_id,client_id,project_id,title,due_at,requested_by_user_id) values(${context.workspaceId},${data.clientId}::uuid,${data.projectId||null}::uuid,${data.title},${data.dueAt||null}::timestamptz,${context.userId}) returning id,title,status,due_at`;await sql`insert into activities(workspace_id,actor_user_id,entity_type,entity_id,action,metadata) values(${context.workspaceId},${context.userId},'approval',${created.id}::uuid,'CREATED'::activity_action,${JSON.stringify({name:data.title})}::jsonb)`;return [created]});return NextResponse.json({item},{status:201})}catch(error){return apiError(error)} }
