import { NextResponse } from 'next/server'
import { z } from 'zod'
import { requireAuthorization } from '@/lib/server/authorization'
import { db } from '@/lib/server/db'
import { apiError, AppError } from '@/lib/server/errors'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'
const types = ['QUOTATION', 'PROPOSAL', 'CONTRACT', 'INVOICE', 'BILL', 'OTHER'] as const
const input = z.object({ documentType: z.enum(types), name: z.string().trim().min(2).max(160), isDefault: z.boolean().default(false), body: z.record(z.string(), z.unknown()).default({}) })

export async function GET(request: Request) { try { const context = await requireAuthorization(); if (!context.permissions.includes('documents.view')) throw new AppError('FORBIDDEN', 'You do not have permission to view document templates.', 403); const type = new URL(request.url).searchParams.get('type'); if (type && !types.includes(type as typeof types[number])) throw new AppError('VALIDATION_ERROR', 'Document template type is invalid.', 400); const items = await db()`select t.id,t.document_type,t.name,t.is_default,t.created_at,t.updated_at,v.version,v.body from document_templates t join lateral (select version,body from document_template_versions where template_id=t.id order by version desc limit 1) v on true where t.workspace_id=${context.workspaceId} and t.archived_at is null and (${type || ''}='' or t.document_type=${type || ''}) order by t.document_type,t.is_default desc,t.name`; return NextResponse.json({ items }) } catch (error) { return apiError(error) } }
export async function POST(request: Request) { try { const context = await requireAuthorization(); if (!context.permissions.includes('documents.edit')) throw new AppError('FORBIDDEN', 'You do not have permission to manage document templates.', 403); const data = input.parse(await request.json()); const [item] = await db().begin(async sql => { if (data.isDefault) await sql`update document_templates set is_default=false where workspace_id=${context.workspaceId} and document_type=${data.documentType} and archived_at is null`; const [template] = await sql`insert into document_templates(workspace_id,document_type,name,is_default) values(${context.workspaceId},${data.documentType},${data.name},${data.isDefault}) returning id,document_type,name,is_default,created_at`; const [version] = await sql`insert into document_template_versions(template_id,version,body,created_by_user_id) values(${template.id}::uuid,1,${JSON.stringify(data.body)}::jsonb,${context.userId}::uuid) returning version,body`; await sql`insert into activities(workspace_id,actor_user_id,entity_type,entity_id,action,metadata) values(${context.workspaceId},${context.userId},'document_template',${template.id}::uuid,'CREATED'::activity_action,${JSON.stringify({ name: data.name, documentType: data.documentType })}::jsonb)`; return [{ ...template, ...version }] }); return NextResponse.json({ item }, { status: 201 }) } catch (error) { return apiError(error) } }
