'use client'

import React, { useEffect, useState } from 'react'
import { ActiveMemberSelector } from './active-member-selector'
import { FormSelect } from './form-select'
import type { Client } from '@/lib/qnl-mock'
import { Building2, Check, CircleDollarSign, FileText, Globe2, Hash, Landmark, Link, MapPin, Phone, UserRound, UsersRound, X } from 'lucide-react'

const draftKey = 'qnl-client-create-draft-v1'
type FormData = { name:string; kind:string; email:string; phone:string; website:string; status:string; ownerUserId:string; shortName:string; industry:string; description:string; contactName:string; designation:string; addressLine1:string; addressLine2:string; city:string; state:string; postalCode:string; country:string; taxId:string; paymentTerms:string; currency:string; sendWelcome:boolean }
const initialForm: FormData = { name:'', kind:'ORGANIZATION', email:'', phone:'', website:'', status:'ACTIVE', ownerUserId:'', shortName:'', industry:'', description:'', contactName:'', designation:'', addressLine1:'', addressLine2:'', city:'', state:'', postalCode:'', country:'India', taxId:'', paymentTerms:'30 days', currency:'INR (₹)', sendWelcome:true }
const sections = [['general','General',UsersRound],['contact','Contact Details',Phone],['address','Address',MapPin],['business','Business Info',Building2]] as const
const locations: Record<string, Record<string, string[]>> = { India: { Karnataka: ['Bengaluru', 'Mysuru'], Maharashtra: ['Mumbai', 'Pune'], 'Tamil Nadu': ['Chennai', 'Coimbatore'], Delhi: ['New Delhi'] }, 'United States': { California: ['Los Angeles', 'San Francisco'], 'New York': ['New York City', 'Buffalo'], Texas: ['Austin', 'Dallas'] }, 'United Kingdom': { England: ['London', 'Manchester'], Scotland: ['Edinburgh', 'Glasgow'] } }

type DialogProps = { onClose: () => void; onCreated: () => Promise<void>; client?: Client }
export function ClientCreateDialog(props: Omit<DialogProps, 'client'>) { return <ClientDialog {...props} /> }
export function ClientEditDialog({ client, onSaved, onClose }: { client: Client; onClose: () => void; onSaved: () => Promise<void> }) { return <ClientDialog client={client} onClose={onClose} onCreated={onSaved} /> }
function ClientDialog({ onClose, onCreated, client }: DialogProps) {
  const editing = Boolean(client)
  const [form,setForm] = useState<FormData>(() => client ? { ...initialForm, name:client.name, kind:client.kind === 'Individual' ? 'INDIVIDUAL' : 'ORGANIZATION', email:client.email || '', phone:client.phone || '', website:client.website || '', status:client.status === 'Reviewing' ? 'REVIEWING' : client.status === 'Inactive' ? 'INACTIVE' : 'ACTIVE', ownerUserId:client.ownerUserId || '', shortName:client.shortName || '', industry:client.industry || '', description:client.description || '', contactName:client.contactName || '', designation:client.designation || '', addressLine1:client.addressLine1 || '', addressLine2:client.addressLine2 || '', city:client.city || '', state:client.state || '', postalCode:client.postalCode || '', country:client.country || 'India', taxId:client.taxId || '', paymentTerms:client.paymentTerms || '30 days', currency:client.currency || 'INR (₹)', sendWelcome:false } : initialForm), [permissions,setPermissions] = useState<string[]>([]), [saving,setSaving] = useState(false), [error,setError] = useState(''), [activeSection,setActiveSection] = useState('general'), [draftReady,setDraftReady] = useState(false)
  useEffect(() => { void fetch('/api/me').then(r => r.ok ? r.json() : null).then(me => setPermissions(me?.permissions || [])) }, [])
  useEffect(() => { if (editing) { setDraftReady(true); return } try { const saved = localStorage.getItem(draftKey); if (saved) { const draft = JSON.parse(saved) as { form?: Partial<FormData>; activeSection?: string; savedAt?: number }; if (draft.form && (!draft.savedAt || Date.now() - draft.savedAt < 1000 * 60 * 60 * 24 * 14)) { setForm(current => ({ ...current, ...draft.form })); if (sections.some(([id]) => id === draft.activeSection)) setActiveSection(draft.activeSection!) } else localStorage.removeItem(draftKey) } } catch { localStorage.removeItem(draftKey) } finally { setDraftReady(true) } }, [editing])
  useEffect(() => { if (!editing && draftReady) localStorage.setItem(draftKey, JSON.stringify({ form, activeSection, savedAt: Date.now() })) }, [form, activeSection, draftReady, editing])
  const set = <K extends keyof FormData>(key:K, value:FormData[K]) => setForm(current => ({...current,[key]:value}))
  const discard = () => { if (!editing) localStorage.removeItem(draftKey); onClose() }
  const activeIndex = sections.findIndex(([id]) => id === activeSection)
  const goTo = (id:string) => { setError(''); setActiveSection(id) }
  const navigate = (event: React.MouseEvent<HTMLButtonElement>, id: string) => { event.preventDefault(); event.stopPropagation(); goTo(id) }
  const submit = async (event:React.FormEvent) => { event.preventDefault(); const name = form.name.trim(), email = form.email.trim(), phone = form.phone.trim(), website = form.website.trim(); if (name.length < 2) { goTo('general'); setError('Company name must contain at least 2 characters.'); return } if (email && !/^\S+@\S+\.\S+$/.test(email)) { goTo('contact'); setError('Enter a valid email address.'); return } setSaving(true); setError(''); try { const body={...form,name,website,...(permissions.includes('clients.assign')&&form.ownerUserId?{ownerUserId:form.ownerUserId}:{})}, response=await fetch(`/api/clients${client ? `/${client.id}` : ''}`,{method:client?'PATCH':'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify(body)}), result=await response.json(); if(!response.ok) throw new Error(result.error?.message||`Unable to ${editing?'update':'create'} client.`); if (!editing) localStorage.removeItem(draftKey); await onCreated() } catch(cause) { setError(cause instanceof Error?cause.message:`Unable to ${editing?'update':'create'} client.`) } finally { setSaving(false) } }
  return <div className="modal-backdrop client-create-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) discard() }}><form className="client-create-dialog" noValidate onMouseDown={e=>e.stopPropagation()} onSubmit={submit}>
    <header className="client-create-header"><div className="client-create-mark"><UsersRound/></div><div><div className="client-create-eyebrow">{editing?'Edit client':'Create client'}</div><h2>{editing?`Edit ${client!.name}`:'New Client'}</h2><p>{editing?'Update this client’s details across all four sections.':'Add a new client to your workspace. Fill in the details below to get started.'}</p></div><button type="button" className="client-create-close" onClick={discard} aria-label="Close client dialog"><X/></button></header>
    <div className="client-create-layout"><nav className="client-create-nav" aria-label="Client form sections"><div className="client-step-count">Step {activeIndex+1} of {sections.length}</div>{sections.map(([id,label,Icon])=><button key={id} type="button" className={activeSection===id?'active':''} onClick={event=>navigate(event,id)}><Icon/><span>{label}</span></button>)}</nav><main className={`client-create-body client-step-${activeSection}`}>
      <section data-section="general"><Heading title="General Information" description="Basic details about the client."/><div className="client-type"><Field label="Client type" required><Select icon={<Building2/>} value={form.kind} onChange={v=>set('kind',v)}><option value="ORGANIZATION">Organization</option><option value="INDIVIDUAL">Individual</option></Select></Field></div><div className="client-field-grid"><Field label="Company name" required><Input icon={<Building2/>} autoFocus required placeholder="Enter company name" value={form.name} onChange={e=>set('name',e.target.value)}/></Field><Field label="Short name / Code"><Input icon={<Hash/>} placeholder="e.g. QNL" value={form.shortName} onChange={e=>set('shortName',e.target.value)}/></Field><Field label="Industry"><Select icon={<FileText/>} value={form.industry} onChange={v=>set('industry',v)}><option value="">Select industry</option><option>Technology</option><option>Professional services</option><option>Manufacturing</option><option>Cafe / Restaurant</option><option>Education / School</option><option>Healthcare</option><option>Retail / E-commerce</option><option>Construction / Real estate</option><option>Hospitality / Travel</option><option>Finance / Insurance</option><option>Media / Entertainment</option><option>Logistics / Transportation</option><option>Non-profit / NGO</option><option>Government / Public sector</option><option>Legal services</option><option>Marketing / Advertising</option><option>Food / Beverage</option><option>Fitness / Wellness</option><option>Automotive</option><option>Agriculture</option><option>Other</option></Select></Field><Field label="Website"><Input icon={<Link/>} type="url" placeholder="https://www.company.com" value={form.website} onChange={e=>set('website',e.target.value)}/></Field></div><Field label="Description"><div className="client-textarea"><textarea maxLength={500} placeholder="Brief description about the client, their business, or notes..." value={form.description} onChange={e=>set('description',e.target.value)}/></div></Field></section>
      <section data-section="contact"><Heading title="Contact Details" description="Primary contact person for this client."/><div className="client-field-grid"><Field label="Contact name" required><Input icon={<UserRound/>} placeholder="Enter contact person name" value={form.contactName} onChange={e=>set('contactName',e.target.value)}/></Field><Field label="Designation"><Input icon={<Landmark/>} placeholder="e.g. Manager, Director" value={form.designation} onChange={e=>set('designation',e.target.value)}/></Field><Field label="Email" required><Input icon={<FileText/>} type="email" placeholder="name@company.com" value={form.email} onChange={e=>set('email',e.target.value)}/></Field><Field label="Phone" required><Input icon={<Phone/>} type="tel" placeholder="98765 43210" value={form.phone} onChange={e=>set('phone',e.target.value)}/></Field></div>{permissions.includes('clients.assign')&&<div className="client-owner"><ActiveMemberSelector value={form.ownerUserId} onChange={v=>set('ownerUserId',v)}/></div>}</section>
      <section data-section="address"><Heading title="Address" description="Client's primary business address."/><div className="client-field-grid"><Field label="Address line 1"><Input icon={<MapPin/>} placeholder="Building, street, area" value={form.addressLine1} onChange={e=>set('addressLine1',e.target.value)}/></Field><Field label="Address line 2"><Input icon={<MapPin/>} placeholder="Apartment, suite, unit (optional)" value={form.addressLine2} onChange={e=>set('addressLine2',e.target.value)}/></Field></div><div className="client-address-grid"><Field label="City"><Select icon={<Building2/>} value={form.city} onChange={v=>set('city',v)}><option value="">Select city</option>{form.state && (locations[form.country]?.[form.state] || []).map(city=><option key={city}>{city}</option>)}</Select></Field><Field label="State"><Select icon={<MapPin/>} value={form.state} onChange={v=>{set('state',v);set('city','')}}><option value="">Select state</option>{Object.keys(locations[form.country] || {}).map(state=><option key={state}>{state}</option>)}</Select></Field><Field label="PIN / Postal code"><Input icon={<Hash/>} placeholder="Enter PIN code" value={form.postalCode} onChange={e=>set('postalCode',e.target.value)}/></Field><Field label="Country"><Select icon={<Globe2/>} value={form.country} onChange={v=>{set('country',v);set('state','');set('city','')}}><option>India</option><option>United States</option><option>United Kingdom</option></Select></Field></div></section>
      <section data-section="business"><Heading title="Business Information" description="Additional business details."/><div className="client-business-grid"><Field label="Tax ID / GSTIN"><Input icon={<FileText/>} placeholder="Enter GSTIN / Tax ID (optional)" value={form.taxId} onChange={e=>set('taxId',e.target.value)}/></Field><Field label="Payment terms (days)"><Select icon={<CircleDollarSign/>} value={form.paymentTerms} onChange={v=>set('paymentTerms',v)}><option value="0 days">Due on receipt</option>{Array.from({ length: 90 }, (_, index) => <option key={index + 1}>{index + 1} {index === 0 ? 'day' : 'days'}</option>)}</Select></Field><Field label="Currency"><Select icon={<CircleDollarSign/>} value={form.currency} onChange={v=>set('currency',v)}><option>INR (₹)</option><option>USD ($)</option><option>GBP (£)</option></Select></Field>{editing&&<Field label="Status"><Select icon={<Check/>} value={form.status} onChange={v=>set('status',v)}><option value="ACTIVE">Active</option><option value="REVIEWING">Reviewing</option><option value="INACTIVE">Inactive</option></Select></Field>}</div></section>
      </main></div>
     {error&&<p className="form-error client-create-error">{error}</p>}<footer className="client-create-footer">{editing?<span/>:<label className="client-welcome"><input type="checkbox" checked={form.sendWelcome} onChange={e=>set('sendWelcome',e.target.checked)}/><i aria-hidden="true">✓</i><span><b>Send welcome email to the client</b><small>They will receive an invitation to access the client portal.</small></span></label>}<div className="modal-actions"><button type="button" className="button button-subtle" onClick={discard}>Cancel</button>{activeIndex>0&&<button type="button" className="button button-subtle" onClick={event=>navigate(event,sections[activeIndex-1][0])}>Back</button>}{activeIndex<sections.length-1?<button type="button" className="button button-primary client-submit" onClick={event=>navigate(event,sections[activeIndex+1][0])}>Continue <span>→</span></button>:<button type="submit" className="button button-primary client-submit" disabled={saving}>{saving?(editing?'Saving…':'Creating…'):(editing?'Save changes':'Create client')} <span>→</span></button>}</div></footer>
  </form></div>
}
function Heading({title,description}:{title:string;description:string}) { return <div className="client-section-heading"><h3>{title}</h3><p>{description}</p></div> }
function Field({label,required,children}:{label:string;required?:boolean;children:React.ReactNode}) { return <label className="client-field-label"><span>{label}{required&&<b> *</b>}</span>{children}</label> }
function Input({icon,...props}:React.InputHTMLAttributes<HTMLInputElement>&{icon:React.ReactNode}) { return <span className="client-icon-input">{icon}<input {...props}/></span> }
function Select({ icon, value, onChange, children }: { icon: React.ReactNode; value: string; onChange: (value: string) => void; children: React.ReactNode }) {
  const options = React.Children.toArray(children).flatMap(child => React.isValidElement<{ value?: string; children?: React.ReactNode }>(child) ? [{ value: child.props.value ?? String(child.props.children), label: child.props.children }] : [])
  return <FormSelect icon={icon} value={value} options={options} ariaLabel="Select an option" onChange={onChange} />
}
