'use client'

import { BriefcaseBusiness, CalendarDays, Check, CircleDollarSign, FileText, Flag, Hash, Tags, UsersRound, X } from 'lucide-react'
import React, { useEffect, useRef, useState } from 'react'
import { ActiveMemberSelector } from './active-member-selector'
import { FormSelect } from './form-select'
import { PROJECT_TYPES } from '@/lib/project-requirement-templates'

const draftKey = 'qnl-project-create-draft-v1'
type Client = { id: string; name: string }
type Form = { name:string; clientId:string; projectType:string; description:string; startDate:string; targetEndDate:string; estimatedDuration:string; status:string; ownerUserId:string; priority:string; tags:string; budget:string; currency:string; notes:string; notifyTeam:boolean }
const today = () => { const date = new Date(), month = String(date.getMonth() + 1).padStart(2, '0'), day = String(date.getDate()).padStart(2, '0'); return `${date.getFullYear()}-${month}-${day}` }
const initial: Form = { name:'', clientId:'', projectType:'', description:'', startDate:today(), targetEndDate:'', estimatedDuration:'', status:'PLANNED', ownerUserId:'', priority:'NORMAL', tags:'', budget:'', currency:'INR', notes:'', notifyTeam:true }
const sections = ['General','Timeline','People','Budget'] as const

export function ProjectCreateDialog({ onClose, onCreated }: { onClose: () => void; onCreated: () => Promise<void> }) {
  const [form,setForm] = useState(initial), [clients,setClients] = useState<Client[]>([]), [active,setActive] = useState<typeof sections[number]>('General'), [error,setError] = useState(''), [saving,setSaving] = useState(false), [draftReady,setDraftReady] = useState(false)
  const createRequestId = useRef(crypto.randomUUID())
  const set = <K extends keyof Form>(key: K, value: Form[K]) => setForm(current => ({ ...current, [key]: value }))
  const discard = () => { localStorage.removeItem(draftKey); onClose() }
  useEffect(() => { void fetch('/api/clients?limit=100', { credentials:'include' }).then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || 'Unable to load clients.'); setClients(body.items) }).catch(cause => setError(cause instanceof Error ? cause.message : 'Unable to load clients.')) }, [])
  useEffect(() => { try { const saved = localStorage.getItem(draftKey); if (saved) { const draft = JSON.parse(saved) as { form?: Partial<Form>; active?: typeof sections[number]; savedAt?: number }; if (draft.form && (!draft.savedAt || Date.now() - draft.savedAt < 1000 * 60 * 60 * 24 * 14)) { setForm(current => ({ ...current, ...draft.form })); if (draft.active && sections.includes(draft.active)) setActive(draft.active) } else localStorage.removeItem(draftKey) } } catch { localStorage.removeItem(draftKey) } finally { setDraftReady(true) } }, [])
  useEffect(() => { if (draftReady) localStorage.setItem(draftKey, JSON.stringify({ form, active, savedAt: Date.now() })) }, [form, active, draftReady])
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (saving) return; const currentStep = sections.indexOf(active); if (currentStep < sections.length - 1) { setError(''); setActive(sections[currentStep + 1]); return } const budget = form.budget ? Number(form.budget.replace(/,/g, '')) : undefined; if (!form.name.trim() || !form.clientId || !form.projectType || !form.startDate || !form.targetEndDate || !form.ownerUserId) { setError('Complete the required project, client, project type, timeline, and owner fields.'); return } if (budget !== undefined && !Number.isFinite(budget)) { setError('Enter a valid budget amount.'); return } setSaving(true); setError(''); try { const response = await fetch('/api/projects', { method:'POST', credentials:'include', headers:{'content-type':'application/json', 'Idempotency-Key': createRequestId.current}, body:JSON.stringify({ ...form, name:form.name.trim(), tags:form.tags.split(',').map(tag => tag.trim()).filter(Boolean), budget }) }), body = await response.json(); if (!response.ok) throw new Error(body.error?.message || 'Unable to create project.'); localStorage.removeItem(draftKey); await onCreated() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to create project.') } finally { setSaving(false) } }
  const index = sections.indexOf(active)
  return <div className="modal-backdrop client-create-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) discard() }}><form className="client-create-dialog project-create-dialog" onSubmit={submit} onMouseDown={event => event.stopPropagation()}>
    <header className="client-create-header"><div className="client-create-mark"><BriefcaseBusiness/></div><div><div className="client-create-eyebrow">Create project</div><h2>New Project</h2><p>Set up a new project to track work, manage tasks, and collaborate with your team.</p></div><button type="button" className="client-create-close" onClick={discard} aria-label="Close project dialog"><X/></button></header>
    <div className="client-create-layout"><nav className="client-create-nav" aria-label="Project form sections">{sections.map((section, step) => <button key={section} type="button" className={active === section ? 'active' : ''} onClick={() => { setError(''); setActive(section) }}><span className="project-step-icon">{step === 0 ? <BriefcaseBusiness/> : step === 1 ? <CalendarDays/> : step === 2 ? <UsersRound/> : <CircleDollarSign/>}</span><span>{section}<small>{['Basic information','Schedule and deadlines','Owner and team','Financial details'][step]}</small></span></button>)}</nav>
    <main className="client-create-body"><section><div className="client-section-heading"><h3>{active === 'General' ? 'General Information' : active === 'Timeline' ? 'Timeline' : active === 'People' ? 'People' : 'Additional Information'}</h3><p>{active === 'General' ? 'Add the key details about your project.' : active === 'Timeline' ? 'Set the project schedule and key dates.' : active === 'People' ? 'Assign ownership and team members.' : 'Add financial context and notes.'}</p></div>
    {active === 'General' && <><div className="client-field-grid"><Field label="Project name" required><Input icon={<BriefcaseBusiness/>} autoFocus value={form.name} placeholder="Enter project name" onChange={event => set('name', event.target.value)}/></Field><Field label="Client" required><Select icon={<UsersRound/>} value={form.clientId} onChange={value => set('clientId',value)}><option value="">Select a client</option>{clients.map(client => <option key={client.id} value={client.id}>{client.name}</option>)}</Select></Field><Field label="Project code"><Input icon={<Hash/>} value="Generated on creation" disabled aria-label="Project code is generated on creation"/></Field><Field label="Project type" required><Select icon={<BriefcaseBusiness/>} value={form.projectType} onChange={value => set('projectType',value)}><option value="">Select project type</option>{PROJECT_TYPES.map(type => <option key={type} value={type}>{type}</option>)}</Select></Field></div><Field label="Description"><div className="client-textarea"><FileText/><textarea maxLength={1000} value={form.description} placeholder="Provide a short description about the project, its goals, and scope..." onChange={event => set('description',event.target.value)}/><span>{form.description.length}/1000</span></div></Field></>}
    {active === 'Timeline' && <div className="client-field-grid"><Field label="Start date" required><Input icon={<CalendarDays/>} type="date" value={form.startDate} onChange={event => set('startDate',event.target.value)}/></Field><Field label="Target end date" required><Input icon={<CalendarDays/>} type="date" value={form.targetEndDate} onChange={event => set('targetEndDate',event.target.value)}/></Field><Field label="Estimated duration"><Input icon={<CalendarDays/>} value={form.estimatedDuration} placeholder="e.g. 3 months" onChange={event => set('estimatedDuration',event.target.value)}/></Field><Field label="Status"><Select icon={<Check/>} value={form.status} onChange={value => set('status',value)}><option value="PLANNED">Planned</option><option value="ACTIVE">Active</option><option value="ON_HOLD">On hold</option></Select></Field></div>}
    {active === 'People' && <div className="client-field-grid"><ActiveMemberSelector label="Project owner *" value={form.ownerUserId} onChange={value => set('ownerUserId',value)}/><Field label="Team members"><span className="form-hint">Team assignments will be added with task workflows.</span></Field><Field label="Priority"><Select menuPosition="up" icon={<Flag/>} value={form.priority} onChange={value => set('priority',value)}><option value="LOW">Low</option><option value="NORMAL">Normal</option><option value="HIGH">High</option><option value="URGENT">Urgent</option></Select></Field><Field label="Tags"><Input icon={<Tags/>} value={form.tags} placeholder="Comma-separated tags" onChange={event => set('tags',event.target.value)}/></Field></div>}
    {active === 'Budget' && <div className="client-field-grid"><Field label="Budget (optional)"><Input icon={<CircleDollarSign/>} inputMode="decimal" pattern="[0-9]*[.,]?[0-9]*" value={form.budget} placeholder="e.g. 50,000" onChange={event => set('budget',event.target.value.replace(/[^0-9.,]/g,''))}/></Field><Field label="Currency"><Select icon={<CircleDollarSign/>} value={form.currency} onChange={value => set('currency',value)}><option value="INR">INR (₹)</option><option value="USD">USD ($)</option><option value="GBP">GBP (£)</option></Select></Field></div>}{active === 'Budget' && <Field label="Notes"><div className="client-textarea"><FileText/><textarea maxLength={500} value={form.notes} placeholder="Add any additional notes or context..." onChange={event => set('notes',event.target.value)}/><span>{form.notes.length}/500</span></div></Field>}
    </section></main></div>{error && <p className="form-error client-create-error">{error}</p>}<footer className="client-create-footer"><label className="client-welcome"><input type="checkbox" checked={form.notifyTeam} onChange={event => set('notifyTeam',event.target.checked)}/><span><b>Notify team members</b><small>Notifications will be available when project team assignments ship.</small></span></label><div className="modal-actions"><button type="button" className="button button-subtle" onClick={discard}>Cancel</button>{index > 0 && <button type="button" className="button button-subtle" onClick={() => setActive(sections[index - 1])}>Back</button>}{index < sections.length - 1 ? <button type="button" className="button button-primary client-submit" onClick={event => { event.preventDefault(); event.stopPropagation(); setError(''); setActive(sections[index + 1]) }}>Continue <span>→</span></button> : <button type="submit" className="button button-primary client-submit" disabled={saving}>{saving ? 'Creating…' : 'Create Project'} <span>→</span></button>}</div></footer>
  </form></div>
}
function Field({ label, required, children }: { label:string; required?:boolean; children:React.ReactNode }) { return <label className="client-field-label"><span>{label}{required && <b> *</b>}</span>{children}</label> }
function Input({ icon, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { icon:React.ReactNode }) { return <span className="client-icon-input">{icon}<input {...props}/></span> }
function Select({ icon, value, onChange, children, menuPosition }: { icon:React.ReactNode; value:string; onChange:(value:string)=>void; children:React.ReactNode; menuPosition?: 'up' }) {
  const options = React.Children.toArray(children).flatMap(child => React.isValidElement<{ value?: string; children?: React.ReactNode }>(child) ? [{ value: child.props.value ?? String(child.props.children), label: child.props.children }] : [])
  return <FormSelect icon={icon} value={value} options={options} ariaLabel="Select an option" menuPosition={menuPosition} onChange={onChange} />
}
