'use client'

import { BriefcaseBusiness, Check, ClipboardList, ChevronRight, UsersRound, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { FormSelect } from './form-select'

type Client = { id: string; name: string }
type Project = { id: string; name: string; client_name: string; client_id: string }
type Form = { title: string; clientId: string; projectId: string; status: 'REQUESTED' | 'REVIEWING' | 'IN_PROGRESS' | 'APPROVED' | 'COMPLETED' | 'REJECTED' }
const initial: Form = { title: '', clientId: '', projectId: '', status: 'REQUESTED' }
const steps = ['Details', 'Routing'] as const

export function RequirementCreateDialog({ onClose, onCreated }: { onClose: () => void; onCreated: () => Promise<void> }) {
  const [form, setForm] = useState<Form>(initial), [clients, setClients] = useState<Client[]>([]), [projects, setProjects] = useState<Project[]>([]), [step, setStep] = useState<typeof steps[number]>('Details'), [saving, setSaving] = useState(false), [loadingOptions, setLoadingOptions] = useState(true), [error, setError] = useState('')
  useEffect(() => { void Promise.all([fetch('/api/clients?limit=100'), fetch('/api/projects')]).then(async ([clientResponse, projectResponse]) => { const clientsBody = await clientResponse.json(), projectsBody = await projectResponse.json(); if (!clientResponse.ok) throw new Error(clientsBody.error?.message || 'Unable to load clients.'); if (!projectResponse.ok) throw new Error(projectsBody.error?.message || 'Unable to load projects.'); setClients(clientsBody.items); setProjects(projectsBody.items) }).catch(cause => setError(cause instanceof Error ? cause.message : 'Unable to load requirement options.')).finally(() => setLoadingOptions(false)) }, [])
  const availableProjects = useMemo(() => projects.filter(project => !form.clientId || project.client_id === form.clientId), [projects, form.clientId])
  const update = <K extends keyof Form>(key: K, value: Form[K]) => setForm(current => ({ ...current, [key]: value, ...(key === 'clientId' ? { projectId: '' } : {}) }))
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!form.title.trim() || !form.clientId) { setError(!form.title.trim() ? 'Enter a requirement title.' : 'Choose a client before creating the requirement.'); setStep(!form.title.trim() ? 'Details' : 'Routing'); return } setSaving(true); setError(''); try { const response = await fetch('/api/requirements', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ title: form.title.trim(), clientId: form.clientId, projectId: form.projectId || null, status: form.status }) }), body = await response.json(); if (!response.ok) throw new Error(body.error?.message || 'Unable to create requirement.'); await onCreated() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to create requirement.') } finally { setSaving(false) } }
  const index = steps.indexOf(step)
  return <div className="modal-backdrop client-create-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><form className="client-create-dialog project-create-dialog" onSubmit={submit} onMouseDown={event => event.stopPropagation()}>
    <header className="client-create-header"><div className="client-create-mark"><ClipboardList /></div><div><div className="client-create-eyebrow">Create requirement</div><h2>New Requirement</h2><p>Capture a clear request and link it to the right client and project.</p></div><button type="button" className="client-create-close" onClick={onClose} aria-label="Close requirement dialog"><X /></button></header>
    <div className="client-create-layout"><nav className="client-create-nav" aria-label="Requirement form sections">{steps.map((item, itemIndex) => <button type="button" key={item} className={step === item ? 'active' : ''} onClick={() => { setError(''); setStep(item) }}><span className="project-step-icon">{itemIndex === 0 ? <ClipboardList /> : <BriefcaseBusiness />}</span><span>{item}<small>{itemIndex === 0 ? 'Request details' : 'Client and workflow'}</small></span></button>)}</nav>
      <main className="client-create-body"><section><div className="client-section-heading"><h3>{step === 'Details' ? 'Requirement details' : 'Route the work'}</h3><p>{step === 'Details' ? 'Use a concise title that describes the requested outcome.' : 'Attach the requirement to its client and optional project.'}</p></div>
        {step === 'Details' && <div className="client-field-grid"><label className="client-field-label"><span>Requirement title<b> *</b></span><span className="client-icon-input"><ClipboardList /><input autoFocus value={form.title} maxLength={240} placeholder="e.g. Add invoice export" onChange={event => update('title', event.target.value)} /></span></label><RequirementSelect label="Initial status" icon={<Check />} value={form.status} placeholder="Requested" options={[{ value: 'REQUESTED', label: 'Requested' }, { value: 'REVIEWING', label: 'Reviewing' }, { value: 'IN_PROGRESS', label: 'In progress' }, { value: 'APPROVED', label: 'Approved' }]} onChange={value => update('status', value as Form['status'])} /></div>}
        {step === 'Routing' && <div className="client-field-grid"><RequirementSelect label="Client" required icon={<UsersRound />} value={form.clientId} placeholder={loadingOptions ? 'Loading clients…' : clients.length ? 'Select a client' : 'No accessible clients'} options={clients.map(client => ({ value: client.id, label: client.name }))} disabled={loadingOptions || !clients.length} onChange={value => update('clientId', value)} /><RequirementSelect label="Project" optional icon={<BriefcaseBusiness />} value={form.projectId} placeholder={!form.clientId ? 'Select a client first' : availableProjects.length ? 'No project' : 'No projects for this client'} options={availableProjects.map(project => ({ value: project.id, label: project.name }))} disabled={!form.clientId || loadingOptions} onChange={value => update('projectId', value)} /></div>}
      </section></main></div>{error && <p className="form-error client-create-error">{error}</p>}<footer className="client-create-footer"><span className="form-hint">Requirement records are immediately available to your workspace.</span><div className="modal-actions"><button type="button" className="button button-subtle" onClick={onClose}>Cancel</button>{index > 0 && <button type="button" className="button button-subtle" onClick={() => setStep(steps[index - 1])}>Back</button>}{index < steps.length - 1 ? <button type="button" className="button button-primary client-submit" onClick={() => setStep(steps[index + 1])}>Continue <ChevronRight size={16} /></button> : <button className="button button-primary client-submit" disabled={saving}>{saving ? 'Creating…' : 'Create Requirement'} <ChevronRight size={16} /></button>}</div></footer>
  </form></div>
}

function RequirementSelect({ label, required, optional, icon, value, placeholder, options, disabled, onChange }: { label: string; required?: boolean; optional?: boolean; icon: React.ReactNode; value: string; placeholder: string; options: { value: string; label: string }[]; disabled?: boolean; onChange: (value: string) => void }) {
  return <label className="client-field-label"><span>{label}{required && <b> *</b>}{optional && <small> (optional)</small>}</span><FormSelect icon={icon} value={value} placeholder={placeholder} options={optional ? [{ value: '', label: 'No project' }, ...options] : options} disabled={disabled} ariaLabel={label} onChange={onChange} /></label>
}
