import { googleAccessToken } from './google-calendar'

type GoogleFile = { id: string; name: string; mimeType: string; size?: string; webViewLink?: string; modifiedTime?: string; parents?: string[] }
const api = 'https://www.googleapis.com/drive/v3'
type GoogleRequest = { method?: string; headers?: Record<string, string>; body?: string }
async function request(workspaceId: string, path: string, init: GoogleRequest = {}) { const token = await googleAccessToken(workspaceId, 'GOOGLE_DRIVE'); if (!token) throw new Error('Connect Google Drive in Settings before using Drive sync.'); const response = await fetch(`${api}${path}`, { ...init, headers: { authorization: `Bearer ${token.access_token}`, ...(init.headers || {}) } }); const body = await response.json() as GoogleFile & { files?: GoogleFile[]; error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message || 'Google Drive request failed.'); return body }
export async function createGoogleFolder(workspaceId: string, name: string, parentId?: string | null) { return request(workspaceId, '/files?fields=id,name,mimeType,webViewLink,modifiedTime,parents', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name, mimeType: 'application/vnd.google-apps.folder', ...(parentId ? { parents: [parentId] } : {}) }) }) }
export async function updateGoogleFile(workspaceId: string, id: string, changes: { name?: string; parentId?: string | null }) { if (changes.parentId !== undefined) { const existing = await request(workspaceId, `/files/${encodeURIComponent(id)}?fields=parents`); const removeParents = existing.parents?.join(',') || ''; return request(workspaceId, `/files/${encodeURIComponent(id)}?addParents=${encodeURIComponent(changes.parentId || '')}&removeParents=${encodeURIComponent(removeParents)}&fields=id,name,mimeType,webViewLink,modifiedTime,parents`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify(changes.name ? { name: changes.name } : {}) }) } return request(workspaceId, `/files/${encodeURIComponent(id)}?fields=id,name,mimeType,webViewLink,modifiedTime,parents`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: changes.name }) }) }
export async function trashGoogleFile(workspaceId: string, id: string) { await request(workspaceId, `/files/${encodeURIComponent(id)}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ trashed: true }) }) }
