'use client'

import { ArrowRight, Check, Eye, EyeOff, LockKeyhole, Mail, ShieldCheck } from 'lucide-react'
import Link from 'next/link'
import { FormEvent, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'

function ProductPanel() { return <aside className="saas-auth-panel"><div className="saas-auth-brand"><img src="/qnl-logo-mark.png" alt="" /><span><b>QNL</b><small>QUANTUM NEST LAB</small></span></div><div className="saas-auth-panel-copy"><p className="saas-auth-kicker">ONE WORKSPACE. EVERY TEAM.</p><h1>Work moves faster<br />when everything<br /><em>connects.</em></h1><p>Bring clients, projects, conversations, and execution into one calm operating system.</p></div><div className="saas-auth-benefits">{['A single source of truth', 'Clear project accountability', 'Built for growing teams'].map(item => <span key={item}><Check size={15} />{item}</span>)}</div><div className="saas-auth-panel-footer"><ShieldCheck size={16} /><span>Secure workspace access</span></div></aside> }

export default function SignInPage() {
  const router = useRouter(), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [showPassword, setShowPassword] = useState(false), [error, setError] = useState(''), [pending, setPending] = useState(false)
  useEffect(() => { void fetch('/api/me').then(async response => { if (!response.ok) return; const me = await response.json(); router.replace(me.workspace.companySetupComplete ? '/dashboard' : '/company-setup') }).catch(() => {}) }, [router])
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); setPending(true); try { const response = await fetch('/api/auth/sign-in', { method: 'POST', credentials: 'include', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email, password }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || 'Unable to sign in.'); router.replace('/dashboard'); router.refresh() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to sign in.') } finally { setPending(false) } }
  return <main className="saas-auth"><section className="saas-auth-shell"><ProductPanel /><section className="saas-auth-content"><div className="saas-auth-topline">New to QNL? <Link href="/sign-up">Create an account <ArrowRight size={14} /></Link></div><form className="saas-auth-card" onSubmit={submit}><header><span className="saas-auth-overline">WELCOME BACK</span><h2>Sign in to your workspace</h2><p>Enter your details to continue where you left off.</p></header>{error && <p className="saas-auth-error" role="alert">{error}</p>}<label>Work email<span className="saas-auth-input"><Mail size={18} /><input required value={email} onChange={event => setEmail(event.target.value)} type="email" autoComplete="email" placeholder="you@company.com" /></span></label><label>Password<span className="saas-auth-input"><LockKeyhole size={18} /><input required value={password} onChange={event => setPassword(event.target.value)} type={showPassword ? 'text' : 'password'} autoComplete="current-password" placeholder="Enter your password" /><button type="button" aria-label={showPassword ? 'Hide password' : 'Show password'} onClick={() => setShowPassword(value => !value)}>{showPassword ? <EyeOff size={18} /> : <Eye size={18} />}</button></span></label><Link className="saas-auth-forgot" href="/forgot-password">Forgot password?</Link><button className="saas-auth-submit" type="submit" disabled={pending}>{pending ? 'Signing in…' : <>Sign in <ArrowRight size={18} /></>}</button><p className="saas-auth-legal">By continuing, you agree to the QNL workspace access policies.</p></form></section></section></main>
}
