import { NextResponse } from 'next/server'
import { z } from 'zod'
import { requireAuthorization } from '@/lib/server/authorization'
import { db } from '@/lib/server/db'
import { apiError, AppError } from '@/lib/server/errors'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'
const idSchema = z.string().uuid()
const lineItem = z.object({ description: z.string().trim().min(1).max(1000), quantity: z.number().positive().max(1_000_000), unitPrice: z.number().nonnegative().max(999_999_999), taxRate: z.number().min(0).max(100).default(0), discountAmount: z.number().nonnegative().max(999_999_999).default(0) })
const updateSchema = z.object({ title: z.string().trim().min(2).max(240).optional(), dueAt: z.string().datetime().nullable().optional(), expiresAt: z.string().datetime().nullable().optional(), issueAt: z.string().datetime().nullable().optional(), referenceNumber: z.string().trim().min(1).max(80).nullable().optional(), notes: z.string().trim().max(20_000).nullable().optional(), terms: z.string().trim().max(20_000).nullable().optional(), currency: z.string().trim().min(3).max(8).optional(), lineItems: z.array(lineItem).max(500).optional(), status: z.enum(['SENT', 'APPROVED', 'REJECTED', 'SIGNED', 'VOID']).optional() }).refine(value => Object.keys(value).length > 0, 'Choose a document update.')
type Document = { id: string; title: string; status: string; document_type: string; client_id: string; project_id: string | null }
const transitions: Record<string, readonly string[]> = { DRAFT: ['SENT', 'VOID'], SENT: ['APPROVED', 'REJECTED', 'VOID'], APPROVED: ['SIGNED', 'VOID'], REJECTED: [], SIGNED: [], VOID: [] }
// Compensate for binary floating-point values such as 49.975, which otherwise round down.
const money = (value: number) => Math.round((value + Math.sign(value || 1) * 1e-9) * 100) / 100

export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) {
  try { const context = await requireAuthorization(); if (!context.permissions.includes('documents.view')) throw new AppError('FORBIDDEN', 'You do not have permission to view documents.', 403); const id = idSchema.parse((await params).id); const [item] = await db()`select d.*,c.name as client_name,c.address_line1 as client_address_line1,c.address_line2 as client_address_line2,c.city as client_city,c.state as client_state,c.country as client_country,c.tax_id as client_tax_id,p.name as project_name,w.name as workspace_name,w.legal_name,w.business_email,w.business_phone,w.business_address,w.business_city,w.business_state,w.website,w.tax_id as workspace_tax_id from documents d join clients c on c.id=d.client_id join workspaces w on w.id=d.workspace_id left join projects p on p.id=d.project_id where d.id=${id}::uuid and d.workspace_id=${context.workspaceId} and d.archived_at is null and (${context.role}<>'MEMBER' or c.owner_user_id=${context.userId}::uuid)`; if (!item) throw new AppError('NOT_FOUND', 'Document not found.', 404); const lineItems = await db()`select id,position,description,quantity,unit_price,tax_rate,discount_amount,line_total from document_line_items where document_id=${id}::uuid and workspace_id=${context.workspaceId} order by position`; return NextResponse.json({ item, lineItems }) } catch (error) { return apiError(error) }
}

export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const context = await requireAuthorization(), id = idSchema.parse((await params).id), data = updateSchema.parse(await request.json())
    if (!context.permissions.includes('documents.edit')) throw new AppError('FORBIDDEN', 'You do not have permission to update documents.', 403)
    const [document] = await db()<Document[]>`select d.id,d.title,d.status,d.document_type,d.client_id,d.project_id from documents d join clients c on c.id=d.client_id where d.id=${id}::uuid and d.workspace_id=${context.workspaceId} and d.archived_at is null and (${context.role}<>'MEMBER' or c.owner_user_id=${context.userId}::uuid)`
    if (!document) throw new AppError('NOT_FOUND', 'Document not found.', 404)
    if (data.status && !transitions[document.status]?.includes(data.status)) throw new AppError('VALIDATION_ERROR', `Cannot transition ${document.status} to ${data.status}.`, 400)
    if (data.lineItems && document.status !== 'DRAFT') throw new AppError('VALIDATION_ERROR', 'Line items can only be changed while a document is in draft.', 400)
    const calculations = data.lineItems?.map(item => { const base = money(item.quantity * item.unitPrice), discounted = Math.max(0, money(base - item.discountAmount)), tax = money(discounted * item.taxRate / 100); return { ...item, lineTotal: money(discounted + tax), taxAmount: tax } })
    const subtotal = calculations ? money(calculations.reduce((sum, item) => sum + money(item.quantity * item.unitPrice), 0)) : undefined, discount = calculations ? money(calculations.reduce((sum, item) => sum + item.discountAmount, 0)) : undefined, tax = calculations ? money(calculations.reduce((sum, item) => sum + item.taxAmount, 0)) : undefined, total = calculations ? money(calculations.reduce((sum, item) => sum + item.lineTotal, 0)) : undefined
    const [item] = await db().begin(async sql => { if (calculations) { await sql`delete from document_line_items where document_id=${id}::uuid and workspace_id=${context.workspaceId}`; for (const [position, line] of calculations.entries()) await sql`insert into document_line_items(workspace_id,document_id,position,description,quantity,unit_price,tax_rate,discount_amount,line_total) values(${context.workspaceId},${id}::uuid,${position},${line.description},${line.quantity},${line.unitPrice},${line.taxRate},${line.discountAmount},${line.lineTotal})` } const [updated] = await sql`update documents set title=coalesce(${data.title ?? null},title),due_at=case when ${data.dueAt !== undefined} then ${data.dueAt ?? null}::timestamptz else due_at end,expires_at=case when ${data.expiresAt !== undefined} then ${data.expiresAt ?? null}::timestamptz else expires_at end,issue_at=case when ${data.issueAt !== undefined} then ${data.issueAt ?? null}::timestamptz else issue_at end,reference_number=case when ${data.referenceNumber !== undefined} then ${data.referenceNumber ?? null} else reference_number end,notes=case when ${data.notes !== undefined} then ${data.notes ?? null} else notes end,terms=case when ${data.terms !== undefined} then ${data.terms ?? null} else terms end,currency=coalesce(${data.currency ?? null},currency),subtotal=coalesce(${subtotal ?? null},subtotal),discount_amount=coalesce(${discount ?? null},discount_amount),tax_amount=coalesce(${tax ?? null},tax_amount),total_amount=coalesce(${total ?? null},total_amount),status=coalesce(${data.status ?? null},status),sent_at=case when ${data.status === 'SENT'} then now() else sent_at end,approved_at=case when ${data.status === 'APPROVED'} then now() else approved_at end,signed_at=case when ${data.status === 'SIGNED'} then now() else signed_at end where id=${id}::uuid and workspace_id=${context.workspaceId} returning id,title,document_type,status,subtotal,discount_amount,tax_amount,total_amount,currency`; await sql`insert into activities(workspace_id,actor_user_id,entity_type,entity_id,action,metadata) values(${context.workspaceId},${context.userId},'document',${id}::uuid,${data.status ? 'STATUS_CHANGED' : 'UPDATED'}::activity_action,${JSON.stringify({ name: updated.title, status: data.status, lineItemCount: calculations?.length })}::jsonb)`; return [updated] })
    return NextResponse.json({ item })
  } catch (error) { return apiError(error) }
}
