import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAuthorization } from "@/lib/server/authorization";
import { db } from "@/lib/server/db";
import { apiError, AppError } from "@/lib/server/errors";

export const runtime = "nodejs";
const input = z.object({ name: z.string().trim().min(1).max(500), parentFileId: z.string().uuid().nullable().optional(), isFolder: z.boolean(), mediaType: z.string().trim().max(255).optional(), sizeBytes: z.number().int().nonnegative().optional(), externalKey: z.string().trim().max(1000).optional(), externalUrl: z.string().url().max(2048).optional(), storageLocationId: z.string().uuid().nullable().optional() });
type FileRow = { id: string; name: string; media_type: string | null; size_bytes: number | null; is_folder: boolean; parent_file_id: string | null; external_url: string | null; created_at: string; updated_at: string };
export async function GET(request: Request) { try { const context = await requireAuthorization(); if (!context.permissions.includes("drive.view")) throw new AppError("FORBIDDEN", "You do not have permission to view files.", 403); const url = new URL(request.url), parent = url.searchParams.get("parent"), archived = url.searchParams.get("archived") === "true", search = url.searchParams.get("search")?.trim() || ""; if (parent && !z.string().uuid().safeParse(parent).success) throw new AppError('VALIDATION_ERROR', 'Folder reference is invalid.', 400); const items = await db()<FileRow[]>`select id,name,media_type,size_bytes,is_folder,parent_file_id,external_url,created_at,updated_at from file_objects where workspace_id=${context.workspaceId} and (${archived} = (archived_at is not null)) and (${parent || null}::uuid is not distinct from parent_file_id) and (${search}='' or name ilike ${`%${search}%`}) order by is_folder desc,name`; return NextResponse.json({items}); } catch(error){return apiError(error)} }
export async function POST(request: Request) { try { const context = await requireAuthorization(); const data=input.parse(await request.json()); const permission=data.isFolder?'drive.create_folder':'drive.upload'; if(!context.permissions.includes(permission)) throw new AppError('FORBIDDEN','You do not have permission to create this Drive record.',403); if(data.parentFileId){const [parent]=await db()<{id:string;is_folder:boolean}[]>`select id,is_folder from file_objects where id=${data.parentFileId}::uuid and workspace_id=${context.workspaceId} and archived_at is null`;if(!parent||!parent.is_folder)throw new AppError('VALIDATION_ERROR','Parent folder is invalid.',400)} const [item]=await db().begin(async sql=>{const [created]=await sql<FileRow[]>`insert into file_objects(workspace_id,storage_location_id,uploaded_by_user_id,parent_file_id,name,media_type,size_bytes,external_key,external_url,is_folder) values(${context.workspaceId},${data.storageLocationId||null}::uuid,${context.userId}::uuid,${data.parentFileId||null}::uuid,${data.name},${data.mediaType||null},${data.sizeBytes||null},${data.externalKey||null},${data.externalUrl||null},${data.isFolder}) returning id,name,media_type,size_bytes,is_folder,parent_file_id,external_url,created_at,updated_at`;await sql`insert into activities(workspace_id,actor_user_id,entity_type,entity_id,action,metadata) values(${context.workspaceId},${context.userId},'file',${created.id}::uuid,'CREATED'::activity_action,${JSON.stringify({name:data.name,isFolder:data.isFolder})}::jsonb)`;return [created]});return NextResponse.json({item},{status:201})}catch(error){return apiError(error)} }
