import bcrypt from 'bcryptjs'
import cors from 'cors'
import express, { type NextFunction, type Request, type Response } from 'express'
import { SignJWT, jwtVerify } from 'jose'
import postgres from 'postgres'
import { z } from 'zod'
import { ROLE_PERMISSIONS, type Permission, type Role } from '../../Frontend/lib/authorization-policy.js'
import { canArchiveClient, canAssignClient, canEditClient, canViewRecord } from '../../Frontend/lib/record-access-policy.js'

const env = z.object({ DATABASE_URL: z.string().url(), SESSION_SECRET: z.string().min(32), FRONTEND_ORIGIN: z.string().url().default('http://localhost:3000'), PORT: z.coerce.number().int().positive().default(4000) }).parse(process.env)
const sql = postgres(env.DATABASE_URL, { max: 10 })
const secret = new TextEncoder().encode(env.SESSION_SECRET)
const app = express()
app.use(cors({ origin: env.FRONTEND_ORIGIN, credentials: true }))
app.use(express.json({ limit: '1mb' }))

type TokenIdentity = { userId: string; workspaceId: string }
type AuthorizationContext = TokenIdentity & { membershipId: string; role: Role; membershipStatus: 'ACTIVE'; permissions: readonly Permission[] }
type AuthRequest = Request & { auth?: AuthorizationContext }
type MembershipRow = { id: string; role: Role; status: 'INVITED' | 'ACTIVE' | 'SUSPENDED' | 'REMOVED'; account_status: 'ACTIVE' | 'DISABLED' }
type ClientAccessRow = { id: string; owner_user_id: string | null }
type ProjectAccessRow = { id: string; owner_user_id: string }
type ClientResponse = { id: string; name: string; kind: 'ORGANIZATION' | 'INDIVIDUAL'; email: string | null; phone: string | null; website: string | null; short_name: string | null; industry: string | null; description: string | null; contact_name: string | null; designation: string | null; address_line1: string | null; address_line2: string | null; city: string | null; state: string | null; postal_code: string | null; country: string | null; tax_id: string | null; payment_terms: string | null; currency: string | null; status: 'ACTIVE' | 'REVIEWING' | 'INACTIVE'; owner: { id: string; name: string; email: string } | null; created_at: Date; updated_at: Date }
const passwordSchema = z.string().min(10, 'Use at least 10 characters.').max(128).regex(/[a-z]/, 'Include a lowercase letter.').regex(/[A-Z]/, 'Include an uppercase letter.').regex(/\d/, 'Include a number.').regex(/[^A-Za-z0-9]/, 'Include a symbol.')
const signup = z.object({ name: z.string().trim().min(2).max(120), email: z.string().trim().email().max(255), password: passwordSchema, confirmPassword: passwordSchema.optional() }).refine(data => !data.confirmPassword || data.password === data.confirmPassword, { message: 'Passwords do not match.', path: ['confirmPassword'] })
const websiteInput = z.preprocess(value => { if (typeof value !== 'string') return value; const website = value.trim(); if (!website) return undefined; return /^[a-z][a-z\d+.-]*:\/\//i.test(website) ? website : `https://${website}` }, z.string().url().max(2048).optional())
const optionalText = (max: number) => z.string().trim().max(max).optional().or(z.literal(''))
const clientInput = z.object({ name: z.string().trim().min(2).max(180), kind: z.enum(['ORGANIZATION', 'INDIVIDUAL']).default('ORGANIZATION'), email: z.string().trim().email().max(255).optional().or(z.literal('')), phone: optionalText(40), website: websiteInput, shortName: optionalText(80), industry: optionalText(120), description: optionalText(500), contactName: optionalText(180), designation: optionalText(120), addressLine1: optionalText(255), addressLine2: optionalText(255), city: optionalText(120), state: optionalText(120), postalCode: optionalText(40), country: optionalText(120), taxId: optionalText(120), paymentTerms: optionalText(40), currency: optionalText(40), ownerUserId: z.string().uuid().optional(), status: z.enum(['ACTIVE', 'REVIEWING', 'INACTIVE']).default('ACTIVE') })
const clientUpdateInput = clientInput.partial()
const projectInput = z.object({ name: z.string().trim().min(2).max(180), clientId: z.string().uuid(), projectType: optionalText(120), description: optionalText(1000), startDate: z.string().date(), targetEndDate: z.string().date(), estimatedDuration: optionalText(80), status: z.enum(['PLANNED', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED']).default('PLANNED'), ownerUserId: z.string().uuid(), priority: z.enum(['LOW', 'NORMAL', 'HIGH', 'URGENT']).default('NORMAL'), tags: z.array(z.string().trim().min(1).max(60)).max(20).default([]), budget: z.number().nonnegative().max(999999999999.99).optional(), currency: z.string().trim().min(3).max(8).default('INR'), notes: optionalText(500) }).refine(data => data.targetEndDate >= data.startDate, { message: 'Target end date must be on or after start date.', path: ['targetEndDate'] })
const tokenFor = (identity: TokenIdentity) => new SignJWT(identity).setProtectedHeader({ alg: 'HS256' }).setIssuer('qnl-command-centre').setIssuedAt().setExpirationTime('7d').sign(secret)
const cookie = (request: Request) => request.headers.cookie?.split(';').map(value => value.trim()).find(value => value.startsWith('qnl_session='))?.slice('qnl_session='.length)
const sessionCookie = (response: Response, token: string) => response.cookie('qnl_session', token, { httpOnly: true, sameSite: 'lax', secure: process.env.NODE_ENV === 'production', maxAge: 604800000, path: '/' })

/** Resolves effective access from PostgreSQL on every protected request. JWT role fields are ignored. */
const requireAuth = async (request: AuthRequest, response: Response, next: NextFunction) => {
  const token = cookie(request)
  if (!token) return response.status(401).json({ error: { code: 'UNAUTHORIZED', message: 'Sign in is required.' } })
  try {
    const { payload } = await jwtVerify(token, secret, { issuer: 'qnl-command-centre' })
    if (typeof payload.userId !== 'string' || typeof payload.workspaceId !== 'string') throw new Error('Invalid identity')
    const [membership] = await sql<MembershipRow[]>`select m.id, m.role, m.status, u.account_status from workspace_memberships m join users u on u.id = m.user_id where m.workspace_id = ${payload.workspaceId} and m.user_id = ${payload.userId}`
    if (!membership || membership.status !== 'ACTIVE' || membership.account_status !== 'ACTIVE') return response.status(403).json({ error: { code: 'FORBIDDEN', message: 'Your workspace membership is not active.' } })
    request.auth = { userId: payload.userId, workspaceId: payload.workspaceId, membershipId: membership.id, role: membership.role, membershipStatus: 'ACTIVE', permissions: ROLE_PERMISSIONS[membership.role] }
    next()
  } catch { response.status(401).json({ error: { code: 'UNAUTHORIZED', message: 'Session is invalid or expired.' } }) }
}
const requirePermission = (permission: Permission) => (request: AuthRequest, response: Response, next: NextFunction) => request.auth?.permissions.includes(permission) ? next() : response.status(403).json({ error: { code: 'FORBIDDEN', message: 'You do not have permission for this action.' } })
const clientFor = async (auth: AuthorizationContext, id: string) => { const [client] = await sql<ClientAccessRow[]>`select id, owner_user_id from clients where id = ${id}::uuid and workspace_id = ${auth.workspaceId} and archived_at is null`; return client }
const projectFor = async (auth: AuthorizationContext, id: string) => { const [project] = await sql<ProjectAccessRow[]>`select id, owner_user_id from projects where id = ${id}::uuid and workspace_id = ${auth.workspaceId} and archived_at is null`; return project }
const ownerFor = async (auth: AuthorizationContext, ownerUserId?: string) => { const owner = ownerUserId ?? auth.userId; if (owner !== auth.userId && !canAssignClient(auth)) throw Object.assign(new Error('You do not have permission to assign clients.'), { status: 403, code: 'FORBIDDEN' }); const [membership] = await sql<{ user_id: string }[]>`select user_id from workspace_memberships where workspace_id = ${auth.workspaceId} and user_id = ${owner}::uuid and status = 'ACTIVE'::membership_status`; if (!membership) throw Object.assign(new Error('Client owner must be an active member of this workspace.'), { status: 400, code: 'VALIDATION_ERROR' }); return owner }
const clientResponseFor = async (id: string) => { const [client] = await sql<ClientResponse[]>`select c.*,case when u.id is null then null else json_build_object('id',u.id,'name',u.name,'email',u.email) end as owner from clients c left join users u on u.id=c.owner_user_id where c.id=${id}::uuid`; return client }

app.post('/api/auth/sign-up', async (request, response, next) => { try {
  const data = signup.parse(request.body), email = data.email.toLowerCase(), hash = await bcrypt.hash(data.password, 12)
  const identity = await sql.begin(async tx => { const [user] = await tx<{ id: string }[]>`insert into users (name, first_name, last_name, display_name, email, password_hash) values (${data.name}, ${data.name.split(/\s+/)[0]}, ${data.name.split(/\s+/).slice(1).join(' ') || null}, ${data.name}, ${email}, ${hash}) returning id`; const slug = `${data.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')}-${crypto.randomUUID().slice(0, 8)}`; const [workspace] = await tx<{ id: string }[]>`insert into workspaces (name,slug) values (${`${data.name}'s Workspace`},${slug}) returning id`; await tx`insert into workspace_memberships (workspace_id,user_id,role,status,joined_at) values (${workspace.id},${user.id},'OWNER'::workspace_role,'ACTIVE'::membership_status,now())`; return { userId: user.id, workspaceId: workspace.id } })
  sessionCookie(response, await tokenFor(identity)); response.status(201).json(identity)
} catch (error) { next(error) } })
app.post('/api/auth/sign-in', async (request, response, next) => { try {
  const data = z.object({ email: z.string().email(), password: z.string().min(1) }).parse(request.body)
  const [account] = await sql<{ id: string; workspace_id: string; password_hash: string }[]>`select u.id,m.workspace_id,u.password_hash from users u join workspace_memberships m on m.user_id=u.id where u.email=${data.email.toLowerCase()} and u.account_status='ACTIVE'::account_status and m.status='ACTIVE'::membership_status order by case m.role when 'OWNER' then 0 else 1 end limit 1`
  if (!account || !(await bcrypt.compare(data.password, account.password_hash))) return response.status(401).json({ error: { code: 'UNAUTHORIZED', message: 'Invalid email address or password.' } })
  await sql`update users set last_login_at = now() where id = ${account.id}`; sessionCookie(response, await tokenFor({ userId: account.id, workspaceId: account.workspace_id })); response.json({ userId: account.id, workspaceId: account.workspace_id })
} catch (error) { next(error) } })
app.post('/api/auth/sign-out', (_request, response) => { response.clearCookie('qnl_session', { path: '/' }); response.status(204).end() })

app.get('/api/clients', requireAuth, requirePermission('clients.view'), async (request: AuthRequest, response, next) => { try { const search = String(request.query.search || ''), limit = Math.min(100, Math.max(1, Number(request.query.limit || 25))), page = Math.max(1, Number(request.query.page || 1)), status = ['ACTIVE', 'REVIEWING', 'INACTIVE'].includes(String(request.query.status)) ? String(request.query.status) : null, auth = request.auth!, offset = (page - 1) * limit, where = sql`c.workspace_id=${auth.workspaceId} and c.archived_at is null and (${auth.role} <> 'MEMBER' or c.owner_user_id = ${auth.userId}::uuid) and (${search}='' or c.name ilike ${`%${search}%`}) and (${status}::client_status is null or c.status=${status}::client_status)`, [items, [{ count }]] = await Promise.all([sql<ClientResponse[]>`select c.*,case when u.id is null then null else json_build_object('id',u.id,'name',u.name,'email',u.email) end as owner from clients c left join users u on u.id=c.owner_user_id where ${where} order by c.name limit ${limit} offset ${offset}`, sql<{ count: string }[]>`select count(*)::text as count from clients c where ${where}`]); response.json({ items, total: Number(count), page, limit }) } catch (error) { next(error) } })
app.get('/api/clients/:id', requireAuth, requirePermission('clients.view'), async (request: AuthRequest, response, next) => { try { const auth = request.auth!, client = await clientFor(auth, String(request.params.id)); if (!client || !canViewRecord(auth, { ownerUserId: client.owner_user_id }, 'clients.view_all')) return response.status(404).json({ error: { code: 'NOT_FOUND', message: 'Client not found.' } }); response.json(await clientResponseFor(client.id)) } catch (error) { next(error) } })
app.post('/api/clients', requireAuth, requirePermission('clients.create'), async (request: AuthRequest, response, next) => { try { const data = clientInput.parse(request.body), auth = request.auth!, owner = await ownerFor(auth, data.ownerUserId), created = await sql.begin(async tx => { const [client] = await tx`insert into clients (workspace_id,name,kind,email,phone,website,short_name,industry,description,contact_name,designation,address_line1,address_line2,city,state,postal_code,country,tax_id,payment_terms,currency,status,owner_user_id) values (${auth.workspaceId},${data.name},${data.kind}::client_kind,${data.email || null},${data.phone || null},${data.website || null},${data.shortName || null},${data.industry || null},${data.description || null},${data.contactName || null},${data.designation || null},${data.addressLine1 || null},${data.addressLine2 || null},${data.city || null},${data.state || null},${data.postalCode || null},${data.country || null},${data.taxId || null},${data.paymentTerms || null},${data.currency || null},${data.status}::client_status,${owner}) returning id`; await tx`insert into activities (workspace_id,actor_user_id,entity_type,entity_id,action,metadata) values (${auth.workspaceId},${auth.userId},'client',${client.id},'CREATED'::activity_action,${JSON.stringify({ name: data.name, ownerUserId: owner, status: data.status })}::jsonb)`; return client }); response.status(201).json(await clientResponseFor(created.id)) } catch (error) { next(error) } })
app.patch('/api/clients/:id', requireAuth, requirePermission('clients.edit'), async (request: AuthRequest, response, next) => { try { const data = clientUpdateInput.parse(request.body), auth = request.auth!, existing = await clientFor(auth, String(request.params.id)); if (!existing || !canEditClient(auth, { ownerUserId: existing.owner_user_id })) return response.status(404).json({ error: { code: 'NOT_FOUND', message: 'Client not found.' } }); const owner = data.ownerUserId === undefined ? existing.owner_user_id : await ownerFor(auth, data.ownerUserId); await sql.begin(async tx => { await tx`update clients set name=coalesce(${data.name ?? null},name),kind=coalesce(${data.kind ?? null}::client_kind,kind),email=coalesce(${data.email ?? null},email),phone=coalesce(${data.phone ?? null},phone),website=coalesce(${data.website ?? null},website),short_name=coalesce(${data.shortName ?? null},short_name),industry=coalesce(${data.industry ?? null},industry),description=coalesce(${data.description ?? null},description),contact_name=coalesce(${data.contactName ?? null},contact_name),designation=coalesce(${data.designation ?? null},designation),address_line1=coalesce(${data.addressLine1 ?? null},address_line1),address_line2=coalesce(${data.addressLine2 ?? null},address_line2),city=coalesce(${data.city ?? null},city),state=coalesce(${data.state ?? null},state),postal_code=coalesce(${data.postalCode ?? null},postal_code),country=coalesce(${data.country ?? null},country),tax_id=coalesce(${data.taxId ?? null},tax_id),payment_terms=coalesce(${data.paymentTerms ?? null},payment_terms),currency=coalesce(${data.currency ?? null},currency),status=coalesce(${data.status ?? null}::client_status,status),owner_user_id=${owner},updated_at=now() where id=${existing.id}::uuid`; await tx`insert into activities (workspace_id,actor_user_id,entity_type,entity_id,action,metadata) values (${auth.workspaceId},${auth.userId},'client',${existing.id}::uuid,'UPDATED'::activity_action,${JSON.stringify({ event: owner !== existing.owner_user_id ? 'client_assignment_changed' : data.status !== undefined ? 'client_status_changed' : 'client_edited', oldOwnerUserId: existing.owner_user_id, newOwnerUserId: owner, status: data.status })}::jsonb)` }); response.json(await clientResponseFor(existing.id)) } catch (error) { next(error) } })
app.delete('/api/clients/:id', requireAuth, requirePermission('clients.archive'), async (request: AuthRequest, response, next) => { try { const auth = request.auth!, existing = await clientFor(auth, String(request.params.id)); if (!existing || !canArchiveClient(auth, { ownerUserId: existing.owner_user_id })) return response.status(404).json({ error: { code: 'NOT_FOUND', message: 'Client not found.' } }); await sql.begin(async tx => { await tx`update clients set archived_at=now(),updated_at=now() where id=${existing.id}::uuid`; await tx`insert into activities (workspace_id,actor_user_id,entity_type,entity_id,action,metadata) values (${auth.workspaceId},${auth.userId},'client',${existing.id}::uuid,'ARCHIVED'::activity_action,${JSON.stringify({ event: 'client_archived' })}::jsonb)` }); response.status(204).end() } catch (error) { next(error) } })
app.get('/api/clients/:id/activities', requireAuth, requirePermission('clients.view'), async (request: AuthRequest, response, next) => { try { const auth = request.auth!, client = await clientFor(auth, String(request.params.id)); if (!client || !canViewRecord(auth, { ownerUserId: client.owner_user_id }, 'clients.view_all')) return response.status(404).json({ error: { code: 'NOT_FOUND', message: 'Client not found.' } }); const items = await sql`select a.id,a.action as type,case when a.action='CREATED' then 'Client created' when a.action='ARCHIVED' then 'Client archived' when a.metadata->>'event'='client_assignment_changed' then 'Client owner changed' when a.metadata->>'event'='client_status_changed' then 'Client status changed' else 'Client details updated' end as description,u.name as actor,a.created_at as time from activities a left join users u on u.id=a.actor_user_id where a.workspace_id=${auth.workspaceId} and a.entity_type='client' and a.entity_id=${client.id}::uuid order by a.created_at desc limit 50`; response.json({ items }) } catch (error) { next(error) } })
app.get('/api/clients/:id/related', requireAuth, requirePermission('clients.view'), async (request: AuthRequest, response, next) => { try { const auth = request.auth!, client = await clientFor(auth, String(request.params.id)); if (!client || !canViewRecord(auth, { ownerUserId: client.owner_user_id }, 'clients.view_all')) return response.status(404).json({ error: { code: 'NOT_FOUND', message: 'Client not found.' } }); const items = await sql`select id,'project'::text as type,name as title,status::text as status,updated_at as timestamp from projects where workspace_id=${auth.workspaceId} and client_id=${client.id}::uuid and archived_at is null union all select id,'requirement'::text,title,status,updated_at from requirements where workspace_id=${auth.workspaceId} and client_id=${client.id}::uuid and archived_at is null union all select id,'task'::text,title,status,coalesce(due_at,updated_at) from tasks where workspace_id=${auth.workspaceId} and client_id=${client.id}::uuid and archived_at is null union all select id,'meeting'::text,title,status,coalesce(starts_at,updated_at) from meetings where workspace_id=${auth.workspaceId} and client_id=${client.id}::uuid and archived_at is null union all select id,'document'::text,title,status,updated_at from documents where workspace_id=${auth.workspaceId} and client_id=${client.id}::uuid and archived_at is null union all select id,'finance'::text,title,status,updated_at from finance_records where workspace_id=${auth.workspaceId} and client_id=${client.id}::uuid and archived_at is null order by timestamp desc limit 100`; response.json({ items }) } catch (error) { next(error) } })

app.get('/api/projects', requireAuth, requirePermission('projects.view'), async (request: AuthRequest, response, next) => { try { const auth = request.auth!, search = String(request.query.search || ''), items = await sql`select p.*, c.name as client_name, json_build_object('id',u.id,'name',u.name,'email',u.email) as owner from projects p join clients c on c.id=p.client_id left join users u on u.id=p.owner_user_id where p.workspace_id=${auth.workspaceId} and p.archived_at is null and (${auth.role} <> 'MEMBER' or p.owner_user_id=${auth.userId}::uuid) and (${search}='' or p.name ilike ${`%${search}%`} or coalesce(p.project_code,'') ilike ${`%${search}%`} or c.name ilike ${`%${search}%`}) order by p.updated_at desc`; response.json({ items }) } catch (error) { next(error) } })
app.get('/api/projects/:id', requireAuth, requirePermission('projects.view'), async (request: AuthRequest, response, next) => { try { const auth = request.auth!, project = await projectFor(auth, String(request.params.id)); if (!project || !canViewRecord(auth, { ownerUserId: project.owner_user_id }, 'projects.view_all')) return response.status(404).json({ error: { code: 'NOT_FOUND', message: 'Project not found.' } }); const [item] = await sql`select p.*,c.name as client_name,json_build_object('id',u.id,'name',u.name,'email',u.email) as owner,(select count(*)::int from tasks t where t.workspace_id=${auth.workspaceId} and t.project_id=p.id and t.archived_at is null) as task_count from projects p join clients c on c.id=p.client_id left join users u on u.id=p.owner_user_id where p.id=${project.id}::uuid`; response.json(item) } catch (error) { next(error) } })
app.post('/api/projects', requireAuth, requirePermission('projects.create'), async (request: AuthRequest, response, next) => { try { const data = projectInput.parse(request.body), auth = request.auth!; if (!auth.permissions.includes('projects.assign') && data.ownerUserId !== auth.userId) return response.status(403).json({ error: { code:'FORBIDDEN', message:'You do not have permission to assign project owners.' } }); const client = await clientFor(auth, data.clientId); if (!client || !canViewRecord(auth, { ownerUserId: client.owner_user_id }, 'clients.view_all')) return response.status(400).json({ error: { code:'VALIDATION_ERROR', message:'Client must be an accessible active client in this workspace.' } }); const [member] = await sql`select user_id from workspace_memberships where workspace_id=${auth.workspaceId} and user_id=${data.ownerUserId}::uuid and status='ACTIVE'::membership_status`; if (!member) return response.status(400).json({ error: { code:'VALIDATION_ERROR', message:'Project owner must be an active member of this workspace.' } }); const project = await sql.begin(async tx => { const [created] = await tx`insert into projects (workspace_id,client_id,name,project_type,description,start_date,target_end_date,estimated_duration,status,owner_user_id,priority,tags,budget,currency,notes) values (${auth.workspaceId},${data.clientId}::uuid,${data.name},${data.projectType || null},${data.description || null},${data.startDate}::date,${data.targetEndDate}::date,${data.estimatedDuration || null},${data.status}::project_status,${data.ownerUserId}::uuid,${data.priority}::project_priority,${data.tags},${data.budget ?? null},${data.currency},${data.notes || null}) returning id,project_code`; await tx`insert into activities (workspace_id,actor_user_id,entity_type,entity_id,action,metadata) values (${auth.workspaceId},${auth.userId},'project',${created.id}::uuid,'CREATED'::activity_action,${JSON.stringify({ name:data.name, clientId:data.clientId, ownerUserId:data.ownerUserId, projectCode: created.project_code })}::jsonb)`; return created }); response.status(201).json(project) } catch (error) { next(error) } })
app.use((error: unknown, _request: Request, response: Response, _next: NextFunction) => { if (error instanceof z.ZodError) { const issue = error.issues[0], field = issue?.path.join('.') || 'request'; return response.status(400).json({ error: { code: 'VALIDATION_ERROR', message: `Invalid ${field}: ${issue?.message || 'invalid value'}.` } }) } if (typeof error === 'object' && error && 'status' in error && typeof error.status === 'number') return response.status(error.status).json({ error: { code: 'code' in error && typeof error.code === 'string' ? error.code : 'REQUEST_ERROR', message: error instanceof Error ? error.message : 'Request failed.' } }); if (typeof error === 'object' && error && 'code' in error && error.code === '23505') return response.status(409).json({ error: { code: 'CONFLICT', message: 'A matching record already exists.' } }); console.error(error); response.status(500).json({ error: { code: 'INTERNAL_ERROR', message: 'An unexpected server error occurred.' } }) })
app.listen(env.PORT, () => console.log(`QNL API listening on ${env.PORT}`))
