import { NextResponse } from 'next/server'
import { z } from 'zod'
import { requireAuthorization } from '@/lib/server/authorization'
import { db } from '@/lib/server/db'
import { apiError, AppError } from '@/lib/server/errors'

export const runtime = 'nodejs'
const providers = ['MANUAL', 'GOOGLE_MEET', 'ZOOM', 'MICROSOFT_TEAMS', 'EXTERNAL'] as const
const input = z.object({ clientId: z.string().uuid(), projectId: z.string().uuid().nullable().optional(), title: z.string().trim().min(2).max(240), startsAt: z.string().datetime(), durationMinutes: z.number().int().min(1).max(1440).nullable().optional(), timezone: z.string().trim().min(1).max(80).default('UTC'), provider: z.enum(providers).default('MANUAL'), meetingUrl: z.string().url().max(2048).nullable().optional(), attendees: z.array(z.object({ name: z.string().trim().min(1).max(160), email: z.string().trim().email().max(255).optional() })).max(200).default([]), agenda: z.string().trim().max(10_000).nullable().optional() })
const query = z.object({ status: z.enum(['SCHEDULED', 'COMPLETED', 'CANCELED', 'NO_SHOW']).optional(), provider: z.enum(providers).optional(), from: z.string().datetime().optional(), to: z.string().datetime().optional(), search: z.string().trim().max(240).optional() })
type MeetingRow = { id: string; title: string; status: string; starts_at: string | null; duration_minutes: number | null; timezone: string; provider: string; meeting_url: string | null; attendees: unknown[]; agenda: string | null; notes: string | null; outcome: string | null; sync_state: string; client_id: string; client_name: string; project_id: string | null; project_name: string | null; created_at: string; updated_at: string }

export async function GET(request: Request) { try { const context = await requireAuthorization(); if (!context.permissions.includes('meetings.view')) throw new AppError('FORBIDDEN', 'You do not have permission to view meetings.', 403); const data = query.parse(Object.fromEntries(new URL(request.url).searchParams)); const items = await db()<MeetingRow[]>`select m.id,m.title,m.status,m.starts_at,m.duration_minutes,m.timezone,m.provider,m.meeting_url,m.attendees,m.agenda,m.notes,m.outcome,m.sync_state,m.client_id,c.name as client_name,m.project_id,p.name as project_name,m.created_at,m.updated_at from meetings m join clients c on c.id=m.client_id left join projects p on p.id=m.project_id where m.workspace_id=${context.workspaceId} and m.archived_at is null and (${context.role}<>'MEMBER' or c.owner_user_id=${context.userId}::uuid) and (${data.status || ''}='' or m.status=${data.status || ''}) and (${data.provider || ''}='' or m.provider=${data.provider || ''}) and (${data.from || null}::timestamptz is null or m.starts_at>=${data.from || null}::timestamptz) and (${data.to || null}::timestamptz is null or m.starts_at<=${data.to || null}::timestamptz) and (${data.search || ''}='' or m.title ilike ${`%${data.search || ''}%`} or c.name ilike ${`%${data.search || ''}%`}) order by m.starts_at asc`; return NextResponse.json({ items }) } catch (error) { return apiError(error) } }
export async function POST(request: Request) { try { const context = await requireAuthorization(); if (!context.permissions.includes('meetings.create')) throw new AppError('FORBIDDEN', 'You do not have permission to create meetings.', 403); const data = input.parse(await request.json()); const [client] = await db()<{ id: string }[]>`select id from clients where id=${data.clientId}::uuid and workspace_id=${context.workspaceId} and archived_at is null and (${context.role}<>'MEMBER' or owner_user_id=${context.userId}::uuid)`; if (!client) throw new AppError('VALIDATION_ERROR', 'Choose an accessible active client.', 400); if (data.projectId) { const [project] = await db()<{ id: string }[]>`select id from projects where id=${data.projectId}::uuid and workspace_id=${context.workspaceId} and client_id=${data.clientId}::uuid and archived_at is null`; if (!project) throw new AppError('VALIDATION_ERROR', 'Project must belong to the selected client.', 400) } const [item] = await db().begin(async sql => { const [created] = await sql<MeetingRow[]>`insert into meetings(workspace_id,client_id,project_id,title,starts_at,status,duration_minutes,timezone,provider,meeting_url,attendees,agenda) values(${context.workspaceId},${data.clientId}::uuid,${data.projectId || null}::uuid,${data.title},${data.startsAt}::timestamptz,'SCHEDULED',${data.durationMinutes ?? null},${data.timezone},${data.provider},${data.meetingUrl ?? null},${JSON.stringify(data.attendees)}::jsonb,${data.agenda ?? null}) returning id,title,status,starts_at,duration_minutes,timezone,provider,meeting_url,attendees,agenda,notes,outcome,sync_state,client_id,project_id,created_at,updated_at`; await sql`insert into activities(workspace_id,actor_user_id,entity_type,entity_id,action,metadata) values(${context.workspaceId},${context.userId},'meeting',${created.id}::uuid,'CREATED'::activity_action,${JSON.stringify({ name: data.title, provider: data.provider })}::jsonb)`; return [created] }); return NextResponse.json({ item }, { status: 201 }) } catch (error) { return apiError(error) } }
