'use client'

import { useEffect, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'

type Invitation = { workspaceName: string; role: string; email: string; existingAccount: boolean }
export default function InvitePage() {
  const params = useParams<{ token: string }>(), router = useRouter(), token = params.token
  const [invite, setInvite] = useState<Invitation | null>(null), [name, setName] = useState(''), [password, setPassword] = useState(''), [loading, setLoading] = useState(true), [submitting, setSubmitting] = useState(false), [error, setError] = useState('')
  useEffect(() => { void fetch(`/api/invitations/${encodeURIComponent(token)}`).then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || 'This invitation is unavailable.'); setInvite(body) }).catch(cause => setError(cause instanceof Error ? cause.message : 'This invitation is unavailable.')).finally(() => setLoading(false)) }, [token])
  const accept = async (event: React.FormEvent) => { event.preventDefault(); setSubmitting(true); setError(''); try { const response = await fetch('/api/invitations/accept', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ token, name: invite?.existingAccount ? undefined : name, password: invite?.existingAccount ? undefined : password }) }), body = await response.json(); if (!response.ok) throw new Error(body.error?.message || 'Unable to accept invitation.'); router.replace('/dashboard'); router.refresh() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to accept invitation.') } finally { setSubmitting(false) } }
  if (loading) return <main className="auth-page"><section className="auth-frame"><section className="auth-form-pane"><p>Checking invitation…</p></section></section></main>
  if (!invite) return <main className="auth-page"><section className="auth-frame"><section className="auth-form-pane"><h1>Invitation unavailable</h1><p>{error || 'This invitation is invalid, expired, revoked, or already used.'}</p><button className="auth-submit" onClick={() => router.replace('/sign-in')}>Go to sign in</button></section></section></main>
  if (invite.existingAccount) return <main className="auth-page"><section className="auth-frame"><section className="auth-form-pane"><h1>You’re invited</h1><p>Join {invite.workspaceName} as {invite.role.toLowerCase()}. Sign in using {invite.email}, then reopen this link to accept.</p><button className="auth-submit" onClick={() => router.push('/sign-in')}>Sign in</button></section></section></main>
  return <main className="auth-page"><section className="auth-frame"><section className="auth-form-pane"><form className="auth-form" onSubmit={accept}><header><h1>Join {invite.workspaceName}</h1><p>You’ve been invited as {invite.role.toLowerCase()} using {invite.email}.</p></header>{error && <p className="auth-notice" role="alert">{error}</p>}<label>Full name<input required minLength={2} value={name} onChange={event => setName(event.target.value)} autoComplete="name" /></label><label>Create password<input required minLength={10} type="password" value={password} onChange={event => setPassword(event.target.value)} autoComplete="new-password" /></label><button className="auth-submit" disabled={submitting}>{submitting ? 'Joining…' : 'Accept invitation'}</button></form></section></section></main>
}
