import { db } from '../db'

type ClientOwner = { id: string; name: string; email: string }
export type ClientRow = { id: string; name: string; kind: 'ORGANIZATION' | 'INDIVIDUAL'; email: string | null; phone: string | null; website: string | null; short_name: string | null; industry: string | null; description: string | null; contact_name: string | null; designation: string | null; address_line1: string | null; address_line2: string | null; city: string | null; state: string | null; postal_code: string | null; country: string | null; tax_id: string | null; payment_terms: string | null; currency: string | null; status: 'ACTIVE' | 'REVIEWING' | 'INACTIVE'; owner_user_id: string | null; owner?: ClientOwner | null; project_count?: number; open_item_count?: number; created_at: Date; updated_at: Date; version: number }

export class ClientRepository {
  async list(workspaceId: string, query: { search?: string; status?: string; page: number; limit: number }) {
    const sql = db(), offset = (query.page - 1) * query.limit, search = query.search?.trim() || ''
    const status = query.status && ['ACTIVE', 'REVIEWING', 'INACTIVE'].includes(query.status) ? query.status : null
    const [items, [{ count }]] = await Promise.all([
      sql<ClientRow[]>`select c.id, c.name, c.kind, c.email, c.phone, c.website, c.short_name, c.industry, c.description, c.contact_name, c.designation, c.address_line1, c.address_line2, c.city, c.state, c.postal_code, c.country, c.tax_id, c.payment_terms, c.currency, c.status, c.owner_user_id, c.created_at, c.updated_at, c.version, case when u.id is null then null else json_build_object('id', u.id, 'name', u.name, 'email', u.email) end as owner, (select count(*)::int from projects p where p.client_id=c.id and p.archived_at is null) as project_count, ((select count(*)::int from requirements r where r.client_id=c.id and r.archived_at is null and r.status not in ('COMPLETED','REJECTED')) + (select count(*)::int from tasks t where t.client_id=c.id and t.archived_at is null and t.status <> 'COMPLETED')) as open_item_count from clients c left join users u on u.id = c.owner_user_id where c.workspace_id = ${workspaceId} and c.archived_at is null and (${search} = '' or c.name ilike ${`%${search}%`} or coalesce(c.email, '') ilike ${`%${search}%`}) and (${status}::client_status is null or c.status = ${status}::client_status) order by c.name asc limit ${query.limit} offset ${offset}`,
      sql<{ count: string }[]>`select count(*)::text as count from clients where workspace_id = ${workspaceId} and archived_at is null and (${search} = '' or name ilike ${`%${search}%`} or coalesce(email, '') ilike ${`%${search}%`}) and (${status}::client_status is null or status = ${status}::client_status)`,
    ])
    return { items, total: Number(count), page: query.page, limit: query.limit }
  }
  async find(workspaceId: string, id: string) { const [row] = await db()<ClientRow[]>`select id, name, kind, email, phone, website, status, owner_user_id, created_at, updated_at, version from clients where id = ${id} and workspace_id = ${workspaceId} and archived_at is null`; return row }
  async findByName(workspaceId: string, name: string) { const [row] = await db()<ClientRow[]>`select id, name, kind, email, phone, website, status, owner_user_id, created_at, updated_at, version from clients where workspace_id = ${workspaceId} and lower(name) = lower(${name}) and archived_at is null`; return row }
  async create(workspaceId: string, data: Pick<ClientRow, 'name' | 'kind' | 'email' | 'phone' | 'website' | 'status' | 'owner_user_id'>) { const [row] = await db()<ClientRow[]>`insert into clients (workspace_id, name, kind, email, phone, website, status, owner_user_id) values (${workspaceId}, ${data.name}, ${data.kind}::client_kind, ${data.email}, ${data.phone}, ${data.website}, ${data.status}::client_status, ${data.owner_user_id}) returning id, name, kind, email, phone, website, status, owner_user_id, created_at, updated_at, version`; return row }
  async createWithActivity(workspaceId: string, actorUserId: string, data: Pick<ClientRow, 'name' | 'kind' | 'email' | 'phone' | 'website' | 'status' | 'owner_user_id'>) {
    return db().begin(async sql => { const [row] = await sql<ClientRow[]>`insert into clients (workspace_id, name, kind, email, phone, website, status, owner_user_id) values (${workspaceId}, ${data.name}, ${data.kind}::client_kind, ${data.email}, ${data.phone}, ${data.website}, ${data.status}::client_status, ${data.owner_user_id}) returning id, name, kind, email, phone, website, status, owner_user_id, created_at, updated_at, version`; await sql`insert into activities (workspace_id, actor_user_id, entity_type, entity_id, action, metadata) values (${workspaceId}, ${actorUserId}, 'client', ${row.id}::uuid, 'CREATED'::activity_action, ${JSON.stringify({ name: row.name })}::jsonb)`; return row })
  }
}
